language: node_js
install:
  - npm install
notifications:
  email:
    recipients:
      - i@lenconda.top
    on_success: always
    on_failure: always
node_js:
  - 'lts/*'
deploy:
  provider: npm
  email: 'i@lenconda.top'
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true
script:
  - npm test
